### ISSUE TITLE
Duplicate Symbols in Encoder

### ISSUE THREAD

**Issue by dennis-tra** [yangl1996/riblt#2]
Hi @yangl1996,

first of all, I'm super excited about your paper introducing these rateless invertible bloom lookup tables!

I tried your implementation and played around with it a little. I found that it behaves unexpectedly when adding duplicate symbols to the encoder. 

When setting the example slices to:

```
alice := []item{1, 2, 3, 4, 4, 5, 6, 8, 9, 10} // notice the two 4's
bob := []item{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
```

The decoder says:

```
4 is exclusive to Alice
7 is exclusive to Bob
```

I would have expected the implementation not to say that four is exclusive to Alice. Adding another `4` to Alice's slice removes the message again.

Having read your paper and knowing a bit about invertible bloom filters I can imagine why this is happening. However, my first question would be: is the API contract that one shouldn't add duplicate symbols? Maybe it's written somewhere and I have missed it. Let me know what the expected behaviour is 👍

**Comment by yangl1996** [comment]
Thanks for the interest!!

Your understanding is correct: the API is supposed to work with sets instead of multisets, so each item can only be added once. If one needs to synchronize multisets, a possible solution is to convert the multiset into a set where items are `(item in multiset, count)`.

**Comment by dennis-tra** [comment]
Great, thank you for the clarification!
